### ISSUE TITLE
Apparently RC3-rtc build crashes

### ISSUE THREAD

**Issue by DJATOM** [WolframRhodium/VapourSynth-BM3DCUDA#1]
I just tried to use rtc build and it crashes vsedit silently.
gdb says that it's a segfault.
```
Starting program: C:\vs-r52.1-port\vsedit.exe
[New Thread 17896.0x4fc8]
...
[New Thread 17896.0x2a78]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffeb5796984 in ?? ()
```

**Comment by WolframRhodium** [comment]
Hi, thanks for the message. Could you please check this file to see what error is reported?
[BM3DCUDA_RTC.zip](https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/files/6528422/BM3DCUDA_RTC.zip)

**Comment by DJATOM** [comment]
Now it throws exception
```
2021-05-23 19:32:43.109 Failed to evaluate the script:
Python exception: 'nvrtcCompileProgram(program, std::ssize(opts), opts)' failed: NVRTC_ERROR_BUILTIN_OPERATION_FAILURE
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
File "H:/Encoding/Ergo_Proxy/index/test.vpy", line 30, in 
clip2 = BM3DCUDA(clip, sigma=1.6, radius=1)
File ***/test.vpy", line 15, in BM3DCUDA
clip = bm3d_func(clip, ref=ref, sigma=sigma, block_step=block_step, bm_range=bm_range, radius=radius, ps_num=ps_num, ps_range=ps_range, chroma=chroma, device_id=device_id, fast=fast)
File "src\cython\vapoursynth.pyx", line 2067, in vapoursynth.Function.__call__vapoursynth.
Error: 'nvrtcCompileProgram(program, std::ssize(opts), opts)' failed: NVRTC_ERROR_BUILTIN_OPERATION_FAILURE
--
2021-05-23 19:32:43.120 Core freed but 8 filter instance(s) still exist Core freed but 8 filter instance(s) still exist
```

**Comment by WolframRhodium** [comment]
[nvrtc-builtins64_113.zip](https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/files/6528554/nvrtc-builtins64_113.zip)
Seems that a dependency is missing, which is not shown in the output of `dumpbin`.

**Comment by DJATOM** [comment]
The same exception is thrown.

**Comment by WolframRhodium** [comment]
I can reproduce the problem but I can't solve it now.

It looks like the problem is solved if CUDA 11.3 is installed and the `bin` path is included in the environment variable `PATH`. But the problem appears after I clear the `PATH` and copy those .dll into `plugins64` manually.

I will check it later this day. Sorry for the inconvenience.

**Comment by DJATOM** [comment]
Yes, copying those dlls (nvrtc-builtins64_113, nvrtc64_112_0) into portable folder solves the issue. i can work with that for now. The most adequate solution is probably to make static build.

**Comment by WolframRhodium** [comment]
A static build is not possible with nvrtc. They only provide a dynamic library.

**Comment by DJATOM** [comment]
I see. Then not much can be done here to solve that issue. But
```python3 
from ctypes import *
cdll.LoadLibrary(r'C:\vs-r52.1-port\vapoursynth64\plugins\nvrtc64_112_0.dll')
cdll.LoadLibrary(r'C:\vs-r52.1-port\vapoursynth64\plugins\nvrtc-builtins64_113.dll')
```
is also works.

**Comment by WolframRhodium** [comment]
Thanks for the suggestion.

I remember `vs_mxnet.dll` used to load foreign dll in the same directory as it does. Will that be more convenient?

**Comment by DJATOM** [comment]
Using the same (plugin) directory is fine by me.

**Comment by WolframRhodium** [comment]
I just created a new RC3 release to ease the trouble, hope that fixes it.

**Comment by DJATOM** [comment]
Yes, now it works without extra crutches. Thanks.
