### ISSUE TITLE
Sigma arg array type error with new avs+ ver

### ISSUE THREAD

**Issue by kedaitinh12** [WolframRhodium/VapourSynth-BM3DCUDA#10]
Error here:
https://forum.doom9.org/showthread.php?p=1951979#post1951979

New ver avs+:
https://forum.doom9.org/showthread.php?p=1951911#post1951911

**Comment by kedaitinh12** [comment]
Maybe, you fixed it, sr for disturb
https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/actions/runs/1215772307

**Comment by WolframRhodium** [comment]
Never mind.
