### ISSUE TITLE
HIPify it/OpenCL release

### ISSUE THREAD

**Issue by LuisB79** [WolframRhodium/VapourSynth-BM3DCUDA#16]
is it possible we can get an HIP release or an opencl release for usage with non nvidia graphics cards?

**Comment by WolframRhodium** [comment]
I am sorry that I have no access to an amd gpu on linux.

In terms of OpenCL support, there is [work](https://link.springer.com/article/10.1007/s11554-020-00945-4) that demonstrates impressive performance, but the source code is not available (and some details are missing from my perspective).

**Comment by LuisB79** [comment]
i do, could i help you out?

**Comment by LuisB79** [comment]
> I am sorry that I have no access to an amd gpu on linux.
> 
> In terms of OpenCL support, there is [work](https://link.springer.com/article/10.1007/s11554-020-00945-4) that demonstrates impressive performance, but the source code is not available (and some details are missing from my perspective).

i do have an amd gpu and linux, could i help you out?

**Comment by WolframRhodium** [comment]
That's great. I'll do some testing and translate the code into hip first.

**Comment by LuisB79** [comment]
awesome, if you wish we can use discord or some other platform to comunicate faster

**Comment by WolframRhodium** [comment]
I prefer discord. How can I contact you?

**Comment by LuisB79** [comment]
Bundero#8472 this is my discord

**Comment by LuisB79** [comment]
boo womp

**Comment by adworacz** [comment]
Does ‘boo wimp’ mean that the HIP effort failed? 

I was wondering about this as well. And for reference, HIP code runs on Nvidia cuss cards as well. 

In fact it’s recommended to start with such by the porting docs. 

See: https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-porting-guide.html#porting-a-new-cuda-project

**Comment by LuisB79** [comment]
Yes, dont even bother to tell Wolfram, he stated he is unable to do it.

**Comment by WolframRhodium** [comment]
> Does ‘boo wimp’ mean that the HIP effort failed?
> 
> I was wondering about this as well. And for reference, HIP code runs on Nvidia cuda cards as well.
> 
> In fact it’s recommended to start with such by the porting docs.
> 
> See: https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-porting-guide.html#porting-a-new-cuda-project

I refuse to use HIP on nvidia gpus because it lacks some latest features. I would maintain a separate version of source code for each vendor (nv, amd, intel) someday.

In terms of amd's gpu, the main block is the availability of online-accessible hardware and good software stack. The g4ad instance of aws is the only available hardware but it is on RDNA architecture and provides an old version of hip that usually crashes.

On intel's gpu, initial code of bm3d is actually been written but I am not satisfied with its performance.

**Comment by LuisB79** [comment]
>I would maintain a separate version of source code for each vendor (nv, amd, intel) someday.
at that point just use a tool like hipsycl to have different backends for cuda, hip and one api

>In terms of amd's gpu, the main block is the availability of online-accessible hardware and good software stack. 
There should be other options, rdna2 cards are becoming quite cheap, newer versions of rocm can be edited for use with N23-N21, without mentioning quite a lot of bug fixes.
