### ISSUE TITLE
Reducing blocking?

### ISSUE THREAD

**Issue by Mr-Z-2697** [WolframRhodium/VapourSynth-BM3DCUDA#5]
During some simple tests, I noticed that higher value of block_step will make more blocking when sigma is high, and block_step=8 will cause a few  visible blocking even when sigma is relatively low (~5).

As mawen mentioned is this issue: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/issues/18#issuecomment-233107735, using smaller block_step in final estimate will decrease some artifacts (including blockiness).

Is it possible to do in this implementation?

**Comment by Mr-Z-2697** [comment]
Misoperation, sorry.

**Comment by WolframRhodium** [comment]
Yes, it is possible by specifying `block_step` to a low value if blocking is observed. The parameter is presented in all of the implementations.

**Comment by Mr-Z-2697** [comment]
> Yes, it is possible by specifying `block_step` to a low value if blocking is observed. The parameter is presented in all of the implementations.

Yeah, I'm already doing that.

But what I mean is "using block_step smaller than basic estimate in final estimate".

I mean if the "non-blockiness" of block_step basic and final (5,4) and (3,3) are close, that could still be some performance improvement, right?

**Comment by WolframRhodium** [comment]
Each `bm3dcpu.BM3D` function call only corresponds to one basic estimate or one final estimate. You may use it like
```python3
basic = bm3dcpu.BM3D(src, block_step=5)
final = bm3dcpu.BM3D(src, ref=basic, block_step=4)
```
for your purpose.
```
```

**Comment by Mr-Z-2697** [comment]
> Each `bm3dcpu.BM3D` function call only corresponds to one basic estimate or one final estimate. You may use it like
> ```python3
> basic = bm3dcpu.BM3D(src, block_step=5)
> final = bm3dcpu.BM3D(src, ref=basic, block_step=4)
> ```
> for your purpose.

Well, thank you so much!
